### ISSUE TITLE
errors after instalation. The web just opens blank page with nginx 404 error.

### ISSUE THREAD

**Issue by m1000rr** [5stackgg/5stack-panel#2]
`
Warning: path /matches/[^/]+/backup-rounds/map/.* cannot be used with pathType Prefix
ingress.networking.k8s.io/demos unchanged
Warning: path /(.*) cannot be used with pathType Prefix
ingress.networking.k8s.io/typesense unchanged
Error from server (BadRequest): error when creating "STDIN": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /matches/[^/]+/backup-rounds/map/.* cannot be used with pathType Prefix
Error from server (BadRequest): error when creating "STDIN": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /(.*) cannot be used with pathType Prefix
Error from server (BadRequest): error when creating "STDIN": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /(.*) cannot be used with pathType Prefix
Error from server (BadRequest): error when creating "STDIN": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /(.*) cannot be used with pathType Prefix
5stack Updated
`

**Comment by lukepolo** [comment]
Thanks, someone else also reported this, working on fixing this now

**Comment by lukepolo** [comment]
https://github.com/5stackgg/5stack-panel/pull/3

**Comment by lukepolo** [comment]
fixed! thanks for reporting here!
