### ISSUE TITLE
[BUG] Switching sides post knife round messes up the scoreboard on the panel

### ISSUE THREAD

**Issue by thed4ddy** [5stackgg/5stack-panel#21]
If Team A wins the knife round and switches side, the panel shows Team A scores as Team B's.

Ex: Team A wins knife, switches side and wins 8-2 (Wingman). On the panel it shows that Team B won 8-2
This was on a Dedicated Server Node

![image](https://github.com/user-attachments/assets/ef844daf-9520-4b57-a6a2-56331f7dfaee)

**Comment by lukepolo** [comment]
I tested this a few times and seems to work . may need to gather some logs

**Comment by lukepolo** [comment]
im going to close for now as I've tried to replicate and havent seen other reports.
