### ISSUE TITLE
[FEATURE] core config on game node server 

### ISSUE THREAD

**Issue by Wave55142** [5stackgg/5stack-panel#25]
"FollowCS2ServerGuidelines":false,
It is currently on true on core config
also 
    "PublicChatTrigger": [ "!" ],
    "SilentChatTrigger": [ "/" ],
To be added pls

As WeaponPaints cant load skins applied

**Comment by lukepolo** [comment]
https://github.com/5stackgg/game-server/commit/8e4a19565e964a3ef2d098ac2d0e019941666fdc#diff-ce435f38623d032d25670f2c63a430dfd1a02db661d10c1ef031cbef2f0f0ef0R74
