### ISSUE TITLE
[FEATURE][Plugin][Obvious] Damage report after round

### ISSUE THREAD

**Issue by SpankI** [5stackgg/5stack-panel#55]
Add an damage report after round.
It's much easy to read and familiar to everyone.

[As example ](https://img.spdev.info/images/512892dcc0bd55e6e339286d2910f642.png)

**Comment by lukepolo** [comment]
IMHO cs2 damage report is easier to read 

![image](https://github.com/user-attachments/assets/997dc925-bc1e-414c-9346-fbb51001f8ca)
